### PR TITLE
adding initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
You might wish to also move your screenshots inside the fastlane structure (see [my cheat-sheet](https://gitlab.com/snippets/1895688) for details).

Once merged, my updater will check and fetch updates to these as well – so app and description don't get out-of-sync :wink: Should you add more details (per-release changelogs, screenshots etc), please let me know so I tell my updater to fetch those, too.

### CODE REVIEW

**Comment by christianrowlands** [comment]
I was wondering how to get the updated description to show up in your listing. I will get this updated. Thanks!

**Comment by IzzySoft** [comment]
Once you've merged this, I've enable the "pull" on my end. Then my updater will check for changed files in your Fastlane structure on each new release. And yes, that's the main ide behind it: you know when things change, and have it in your hands what you wish to be reflected in the app's description.

PS: the icon was taken from your repo, I've just applied `optipng` to reduce file size without compromising on image quality.

**Comment by IzzySoft** [comment]
Uh, anything missing that's holding this PR back from being merged, @christianrowlands?

**Comment by christianrowlands** [comment]
Sorry, I wanted to add a couple details to the description, but have been slammed the last few weeks. I will do it now.

**Comment by IzzySoft** [comment]
Thanks! Adjustments from your side are easier after the merge anyway I guess :smile: On a new release, they'd be then pulled along (I'm updating your app's description on my end now for this). Should you want it here before that, just ping me and I can update manually. Same please should you add more files to fastlane (screenshots, per-release changelogs etc), so I can tell my updater to fetch them as well.

**Comment by christianrowlands** [comment]
I just added some screenshots, and will start doing the changelog on the next release. Don't worry about manually doing it as I plan on pushing out an update in the next week or so.

Thanks for the bump on this.

**Pull request merged**
